"use client";
import React, { createContext, useContext } from "react";
import {
	Zap,
	Settings,
	Disc,
	ShieldCheck,
	LucideIcon,
	Download,
} from "lucide-react";
import Product, { ProductSpec } from "@/types/product";

interface FilterOption {
	name: string;
	count: string;
}

interface ProductContextType {
	products: Product[];
	filters: FilterOption[];
}
const products: Product[] = [
	{
		id: 1,
		category: "Vertical",
		badge: "Best Selling",
		title: "Vertical Machining Center",
		model: "VMC-NANO-X8 / X10",
		badge2: "Eco-Line",
		image: "/x8/x8.png",
		download: "/documents/nano-x8.pdf",

		specs: [
			{ icon: Zap, label: "Spindle", value: "12,000 RPM" },
			{ icon: Settings, label: "Tool Slots", value: "24 ATC" },
			{ icon: Disc, label: "Precision", value: "±0.005mm" },
			{ icon: ShieldCheck, label: "Warranty", value: "2 Years" },
		],
		models: [
			{
				name: "VMC-NANO-X8",
				image: "/x8/x8.png",
				download: "/documents/nano-x8.pdf",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy",
						"Without counterweight design that enhances surface accuracy",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations",
					],
					image: "/feature.jpeg",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 48 /48 /40 m/min.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/structure.jpeg",
				},
				travel: [
					{
						item: "X-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "800",
						valI: "31.50",
					},
					{
						item: "Y-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "500",
						valI: "19.69",
					}, //
					{
						item: "Z-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "550",
						valI: "21.65",
					}, //
					{
						item: "Spindle Nose to Table",
						unitM: "mm",
						unitI: "inch",
						valM: "90 - 600",
						valI: "3.54 - 23.62",
					}, //
					{
						item: "Spindle Center to Z-Rail Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "550",
						valI: "21.65",
					}, //
					{
						item: "Three-Axis Guideway",
						unitM: "",
						unitI: "",
						valM: "X Y Z Load Roller Linear Guideway",
						valI: "X Y Z Load Roller Linear Guideway",
					}, //
				],
				table: [
					{
						item: "Table Size",
						unitM: "mm",
						unitI: "inch",
						valM: "1000 x 500",
						valI: "39.37 x 19.69",
					}, //
					{
						item: "T-Slot (Number x Width x Pitch)",
						unitM: "mm",
						unitI: "inch",
						valM: "3 x 18 x 102",
						valI: "3 x 0.71 x 4.02",
					}, //
					{
						item: "Maximum Table Load",
						unitM: "kg",
						unitI: "lb",
						valM: "700",
						valI: "1,543",
					}, //
				],
				spindle: [
					{
						item: "Spindle Taper",
						unitM: "",
						unitI: "",
						valM: "BT-40 (Ø140mm)",
						valI: "BT-40 (Ø140mm)",
					}, //
					{
						item: "Spindle Driven",
						unitM: "",
						unitI: "",
						valM: "Direct Driven (DDS)",
						valI: "Direct Driven (DDS)",
					}, //
					{
						item: "Spindle Speed",
						unitM: "rpm",
						unitI: "rpm",
						valM: "12,000",
						valI: "12,000",
					}, //
					{
						item: "Spindle Motor Torque",
						unitM: "N-m",
						unitI: "ft-lb",
						valM: "96",
						valI: "70.8",
					}, //
				],
				feedRate: [
					{
						item: "X.Y Axis Rapid Traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "40 / 40",
						valI: "1,575 / 1,575",
					}, //
					{
						item: "Z-Axis Rapid Traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "40",
						valI: "1,575",
					}, //
					{
						item: "X.Y.Z Max. Cutting Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "12",
						valI: "472",
					}, //
				],
				atc: [
					{
						item: "ATC Type",
						unitM: "",
						unitI: "",
						valM: "Arm-Type (Tool to Tool)",
						valI: "Arm-Type (Tool to Tool)",
					}, //
					{
						item: "Tool Storage Capacity",
						unitM: "T",
						unitI: "T",
						valM: "24",
						valI: "24",
					}, //
					{
						item: "Tool Change Time (T-T)",
						unitM: "sec",
						unitI: "sec",
						valM: "1.8",
						valI: "1.8",
					}, //
					{
						item: "Max. Tool Diameter x Length",
						unitM: "mm",
						unitI: "inch",
						valM: "Ø100 x 300",
						valI: "Ø3.94 x 11.81",
					}, //
					{
						item: "Max. Tool Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "8",
						valI: "17.6",
					}, //
				],
				motors: [
					{
						item: "Spindle Motor (Rate/Max.)",
						unitM: "kW",
						unitI: "HP",
						valM: "7.5 / 11",
						valI: "10 / 14.7",
					}, //
					{
						item: "X.Y Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "2.0",
						valI: "2.68",
					}, //
					{
						item: "Z Axis Servo Motor (w/ Brake)",
						unitM: "kW",
						unitI: "HP",
						valM: "3.0",
						valI: "4.02",
					}, //
				],
				accuracy: [
					{
						item: "Positioning Accuracy (JIS)",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.008 / 300",
						valI: "± 0.0003",
					}, //
					{
						item: "Repeatability Accuracy (JIS)",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.003",
						valI: "± 0.0001",
					}, //
				],
				physical: [
					{
						item: "External Dimensions (LxWxH)",
						unitM: "mm",
						unitI: "inch",
						valM: "2300 x 2300 x 2400",
						valI: "90.6 x 90.6 x 94.5",
					}, //
					{
						item: "Gross Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "4700",
						valI: "10,362",
					}, //
					{
						item: "Power Required",
						unitM: "kva",
						unitI: "kva",
						valM: "20",
						valI: "20",
					}, //
					{
						item: "Air Pressure Requirement",
						unitM: "kg/cm²",
						unitI: "psi",
						valM: "6 - 8",
						valI: "85 - 114",
					}, //
				],
				standardAccessories: [
					"BT-40 Direct Driven (DDS) 12,000 Rpm",
					"Tool Box & Tools",
					"Air-Blast Through Spindle",
					"Screw Type Chip Conveyor + Cart",
					"Work Lamp / Work LED Light",
					"Tools Length Measuring Equipment",
					"Three Color Light",
					"Arm-Type ATC-24 Tools",
					"Auto Power Off",
					"High Pressure Water & Air-Gun",
					"Auto Lubrication System",
					"Chip Flush System & Nobs",
					"Rigid Tapping & Threading System Operation",
					"Full Splash Guard",
					"Heat Exchanger for Controller Cabinet",
					"USB Interface",
					"Spindle Oil Coolant System",
					"Spindle Cutting Coolant Ring",
				], //
				optionalAccessories: [
					"4th Axis Rotary Table (Ø125 / Ø170 / Ø210 / Ø255mm)",
					"Heavy Spindle Motor (11KW / 18.5KW)",
					"Chain Type Chip Conveyor + Cart",
					"CE Safety Doors System",
					"Semi-Auto Rotary Table APC System",
					"Heavy Spindle Torque Motor",
					'LCD Screen 15"',
					"CE Approved Certification",
				], //
			},
			{
				name: "VMC-NANO-X10",
				image: "/x8/x10.png",
				download: "/documents/nano-x10.pdf",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy",
						"Without counterweight design that enhances surface accuracy",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations",
					],
					image: "/feature.jpeg",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 48 /48 /40 m/min.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/structure.jpeg",
				},
				travel: [
					{
						item: "X-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "1,020",
						valI: "40.16",
					},
					{
						item: "Y-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "550",
						valI: "21.65",
					},
					{
						item: "Z-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "550",
						valI: "21.65",
					},
					{
						item: "Spindle Nose to Table",
						unitM: "mm",
						unitI: "inch",
						valM: "100 - 700",
						valI: "3.94 - 27.56",
					},
					{
						item: "Spindle Center to Z-Rail Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "550",
						valI: "21.65",
					},
					{
						item: "Three-Axis Guideway",
						unitM: "",
						unitI: "",
						valM: "X Y Z Load Roller Linear Guideway",
						valI: "X Y Z Load Roller Linear Guideway",
					},
				],
				table: [
					{
						item: "Table Size",
						unitM: "mm",
						unitI: "inch",
						valM: "1200 x 600",
						valI: "47.24 x 23.62",
					},
					{
						item: "T-Slot (Number x Width x Pitch)",
						unitM: "mm",
						unitI: "inch",
						valM: "5 x 18 x 100",
						valI: "5 x 0.71 x 3.94",
					},
					{
						item: "Maximum Table Load",
						unitM: "kg",
						unitI: "lb",
						valM: "900",
						valI: "1,984",
					},
				],
				spindle: [
					{
						item: "Spindle Taper",
						unitM: "",
						unitI: "",
						valM: "BT-40 (Ø140mm)",
						valI: "BT-40 (Ø140mm)",
					},
					{
						item: "Spindle Driven",
						unitM: "",
						unitI: "",
						valM: "Direct Driven (DDS)",
						valI: "Direct Driven (DDS)",
					},
					{
						item: "Spindle Speed",
						unitM: "rpm",
						unitI: "rpm",
						valM: "12,000",
						valI: "12,000",
					},
				],
				feedRate: [
					{
						item: "X.Y Axis Rapid Traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "36 / 36",
						valI: "1,417 / 1,417",
					},
					{
						item: "Z-Axis Rapid Traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "30",
						valI: "1,181",
					},
					{
						item: "X.Y.Z Max. Cutting Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "12",
						valI: "472",
					},
				],
				atc: [
					{
						item: "ATC Type",
						unitM: "",
						unitI: "",
						valM: "Arm-Type (Tool to Tool)",
						valI: "Arm-Type (Tool to Tool)",
					},
					{
						item: "Tool Storage Capacity",
						unitM: "T",
						unitI: "T",
						valM: "24",
						valI: "24",
					},
					{
						item: "Tool Change Time (T-T)",
						unitM: "sec",
						unitI: "sec",
						valM: "1.8",
						valI: "1.8",
					},
					{
						item: "Max. Tool Diameter x Length",
						unitM: "mm",
						unitI: "inch",
						valM: "Ø100 x 300",
						valI: "Ø3.94 x 11.81",
					},
					{
						item: "Max. Tool Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "8",
						valI: "17.6",
					},
				],
				motors: [
					{
						item: "Spindle Motor (Rate/Max.)",
						unitM: "kW",
						unitI: "HP",
						valM: "7.5 / 11",
						valI: "10 / 14.7",
					},
					{
						item: "X.Y Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "2.0",
						valI: "2.68",
					},
					{
						item: "Z Axis Servo Motor (w/ Brake)",
						unitM: "kW",
						unitI: "HP",
						valM: "3.0",
						valI: "4.02",
					},
				],
				accuracy: [
					{
						item: "Positioning Accuracy (JIS)",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.008 / 300",
						valI: "± 0.0003 / 11.8",
					},
					{
						item: "Repeatability Accuracy (JIS)",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.003",
						valI: "± 0.0001",
					},
				],
				physical: [
					{
						item: "External Dimensions (LxWxH)",
						unitM: "mm",
						unitI: "inch",
						valM: "3300 x 2300 x 2600",
						valI: "129.9 x 90.6 x 102.4",
					},
					{
						item: "Gross Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "5700",
						valI: "12,566",
					},
					{
						item: "Power Required",
						unitM: "kva",
						unitI: "kva",
						valM: "20",
						valI: "20",
					},
					{
						item: "Air Pressure Requirement",
						unitM: "kg/cm²",
						unitI: "psi",
						valM: "6 - 8",
						valI: "85 - 114",
					},
					{
						item: "Ground Clearance",
						unitM: "mm",
						unitI: "inch",
						valM: "2850",
						valI: "112.2",
					},
				],
				standardAccessories: [
					"BT-40 Direct Driven (DDS) 12,000 Rpm",
					"Tool Box & Tools",
					"Air-Blast Through Spindle",
					"Screw Type Chip Conveyor + Cart",
					"Work Lamp / Work LED Light",
					"Tools Length Measuring Equipment",
					"Three Color Light",
					"Arm-Type ATC-24 Tools",
					"Auto Power Off",
					"High Pressure Water & Air-Gun",
					"Auto Lubrication System",
					"Chip Flush System & Nobs",
					"Rigid Tapping & Threading System Operation",
					"Full Splash Guard",
					"Heat Exchanger for Controller Cabinet",
					"USB Interface",
					"Spindle Oil Coolant System",
					"Spindle Cutting Coolant Ring",
				],
				optionalAccessories: [
					"4th Axis Rotary Table (Ø125 / Ø170 / Ø210 / Ø255mm)",
					"Heavy Spindle Motor (11KW / 18.5KW)",
					"Chain Type Chip Conveyor + Cart",
					"CE Safety Doors System",
					"Semi-Auto Rotary Table APC System",
					"Heavy Spindle Torque Motor",
					'LCD Screen 15"',
					"CE Approved Certification",
				],
			},
		],
	},
	{
		id: 2,
		category: "Vertical",
		badge: "High Speed",
		title: "Vertical Machine Center",
		model: "VMC-NV-855 / 1165 / 1370",
		download: "/documents/nv-855.pdf",
		image: "/nv/NV-855-03.png",
		specs: [
			{ icon: Zap, label: "Spindle", value: "12,000 RPM" },
			{ icon: Settings, label: "Arm Type", value: "24 ATC" },
			{ icon: Disc, label: "Precision", value: "±0.003mm" },
			{ icon: ShieldCheck, label: "Warranty", value: "2 Years" },
		],
		models: [
			{
				name: "NV-855",
				image: "/nv/NV-855-03.png",
				download: "/documents/nv-855.pdf",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy",
						"Without counterweight design that enhances surface accuracy",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations",
					],
					image: "/nv/NV-855-01.png",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 48 /48 /40 m/min.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/nv/NV-855-02.png",
				},
				travel: [
					{
						item: "X-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "830",
						valI: "32.68",
					},
					{
						item: "Y-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "550",
						valI: "21.65",
					},
					{
						item: "Z-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "550",
						valI: "21.65",
					},
					{
						item: "Spindle Nose to table",
						unitM: "mm",
						unitI: "inch",
						valM: "135 - 685",
						valI: "5.32 - 26.97",
					},
					{
						item: "Spindle center to Z-Rail travel",
						unitM: "mm",
						unitI: "inch",
						valM: "595",
						valI: "23.43",
					},
					{
						item: "Three-Axis Guideway",
						unitM: "",
						unitI: "",
						valM: "X Y Z  load Roller Linear Guideway",
						valI: "X Y Z  load Roller Linear Guideway",
					},
				],
				table: [
					{
						item: "Table Size",
						unitM: "mm",
						unitI: "inch",
						valM: "1000 x 550",
						valI: "39.37 x 21.65",
					},
					{
						item: "T-Slot ( number*width*picth)",
						unitM: "mm",
						unitI: "inch",
						valM: "5 x 18 x 90",
						valI: "5 x 0.71 x 3.54",
					},
					{
						item: "Maximum table load",
						unitM: "kg",
						unitI: "lb",
						valM: "800",
						valI: "1,764",
					},
				],
				spindle: [
					{
						item: "Spindle taper",
						unitM: "",
						unitI: "",
						valM: "(Ø140mm)    BT-40",
						valI: "(Ø140mm)    BT-40",
					},
					{
						item: "Spindle Driven",
						unitM: "",
						unitI: "",
						valM: "Direct driven  ( DDS)",
						valI: "Direct driven  ( DDS)",
					},
					{
						item: "Spindle Speed",
						unitM: "rpm",
						unitI: "rpm",
						valM: "12,000",
						valI: "12,000",
					},
					{
						item: "Spindle motor Troque",
						unitM: "",
						unitI: "",
						valM: "96",
						valI: "96",
					},
				],
				feedRate: [
					{
						item: "X.Y Axis Rapid traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "40 / 40",
						valI: "1,575 / 1,575",
					},
					{
						item: "Z-Axis Rapid traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "40",
						valI: "1,575",
					},
					{
						item: "X.Y.Z Max. Cutting feed rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "12",
						valI: "472",
					},
				],
				atc: [
					{
						item: "ATC tool changer",
						unitM: "",
						unitI: "",
						valM: "Arm-Type ( Tool to tool)",
						valI: "Arm-Type ( Tool to tool)",
					},
					{
						item: "Tool Storage Capacity",
						unitM: "T",
						unitI: "T",
						valM: "24",
						valI: "24",
					},
					{
						item: "Tool Change Time (T-T)",
						unitM: "sec",
						unitI: "sec",
						valM: "1.8",
						valI: "1.8",
					},
					{
						item: "Max.Tool diameter*adjacent (with Neighbor)",
						unitM: "mm",
						unitI: "inch",
						valM: "80 x 300",
						valI: "3.15 x 11.81",
					},
					{
						item: "Max. Tools weight",
						unitM: "kg",
						unitI: "lb",
						valM: "7",
						valI: "15",
					},
				],
				motors: [
					{
						item: "Spindle Motor (Rate/Max.)",
						unitM: "kW",
						unitI: "HP",
						valM: "7.5 / 11",
						valI: "10.1 / 14.8",
					},
					{
						item: "X.Y Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "2",
						valI: "2.68",
					},
					{
						item: "Z Axis Servo Motor / w Breaks",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.02",
					},
				],
				accuracy: [
					{
						item: "Positioning Accuracy (JIS) Std.",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.008 / 300",
						valI: "± 0.008 / 300",
					},
					{
						item: "Repeatability  Accuracy (JIS) Std.",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.003",
						valI: "± 0.003",
					},
				],
				physical: [
					{
						item: "Power Required (kva/ Electricity Capcity)",
						unitM: "kva",
						unitI: "kva",
						valM: "20",
						valI: "20",
					},
					{
						item: "Air-Pressure Requirement",
						unitM: "kg/cm²",
						unitI: "psi",
						valM: "6 - 8",
						valI: "85 - 114",
					},
					{
						item: "External Dimensions ( L*W*H)",
						unitM: "mm",
						unitI: "inch",
						valM: "2500 x 2200 x 2400",
						valI: "98.43 x 86.61 x 94.49",
					},
					{
						item: "Gross.Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "5,000",
						valI: "11,023",
					},
					{
						item: "Ground Clearance ( height)",
						unitM: "mm",
						unitI: "inch",
						valM: "2500",
						valI: "98.43",
					},
				],
				standardAccessories: [
					"AIR- BLAST THROUGHT SPINDLE",
					"ARM-TYPE ATC-24 TOOLS",
					"AUTO LUBRICATION SYSTEM",
					"AUTO POWER OFF",
					"BT-40 DIRECT DRIVEN ( DDS) 12,000 Rpm",
					"CHIP FLUSH SYSTEM & NOBS",
					"FULL SPLASH GUARD",
					"HEAT EXCHANGER FOR CONTROLLER CABINET",
					"HIGH PRESSURE WATER & AIR-GUN",
					"RIDGIT TAPPING & THREADING SYSTEM OPERATION",
					"SCREW TYPE CHIP CONVEYOR + CART",
					"SPINDLE CUTTING COOLANT RING",
					"SPINDLE OIL COOLANT SYSTEM",
					"THREE COLOR LIGHT",
					"TOOL BOX & TOOLS",
					"TOOLS LENGTH MEASURING EQUIPMENT",
					"UBS INTERFACE",
					"WORK LAMP / WORK LED LIGHT",
				],
				optionalAccessories: [
					"4th AXIS ROTARY TABLE ( Ø125 / Ø170 / Ø210 / Ø255mm)",
					"CE APPROVED CERTIFICATION",
					"CE SAFETY DOORS SYSTEM",
					"CHAIN TYPE CHIP CONVEYOR + CART",
					"HEAVY SPINDLE MOTOR ( 11KW / 18.5KW)",
					"HEAVY SPINDLE TORQUE MOTOR",
					'LCD SCREEN 15"',
					"SEMI-AUTO ROTARY TABLE APC SYSTEM",
				],
			},
			{
				name: "NV-1165",
				image: "/nv/NV-1165-02.png",
				download: "/documents/nv1165.pdf",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy",
						"Without counterweight design that enhances surface accuracy",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations",
					],
					image: "/nv/NV-1165-03.png",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 48 /48 /40 m/min.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/nv/NV- 1165-01.png",
				},
				travel: [
					{
						item: "X-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "1,100",
						valI: "43.31",
					},
					{
						item: "Y-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "650",
						valI: "25.59",
					},
					{
						item: "Z-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "600",
						valI: "23.62",
					},
					{
						item: "Spindle Nose to table",
						unitM: "mm",
						unitI: "inch",
						valM: "120 - 720",
						valI: "4.72 - 28.35",
					},
					{
						item: "Spindle center to Z-Rail travel",
						unitM: "mm",
						unitI: "inch",
						valM: "680",
						valI: "26.77",
					},
					{
						item: "Three-Axis Guideway",
						unitM: "",
						unitI: "",
						valM: "X Y Z  load Roller Linear Guideway",
						valI: "X Y Z  load Roller Linear Guideway",
					},
				],
				table: [
					{
						item: "Table Size",
						unitM: "mm",
						unitI: "inch",
						valM: "1200 x 600",
						valI: "47.24 x 23.62",
					},
					{
						item: "T-Slot ( number*width*picth)",
						unitM: "mm",
						unitI: "inch",
						valM: "5 x 18 x 100",
						valI: "5 x 0.71 x 3.94",
					},
					{
						item: "Maximum table load",
						unitM: "kg",
						unitI: "lb",
						valM: "900",
						valI: "1,984",
					},
				],
				spindle: [
					{
						item: "Spindle taper",
						unitM: "",
						unitI: "",
						valM: "(Ø150mm)    BT-40",
						valI: "(Ø150mm)    BT-40",
					},
					{
						item: "Spindle Driven",
						unitM: "",
						unitI: "",
						valM: "Direct driven  ( DDS)",
						valI: "Direct driven  ( DDS)",
					},
					{
						item: "Spindle Speed",
						unitM: "rpm",
						unitI: "rpm",
						valM: "12,000",
						valI: "12,000",
					},
					{
						item: "Spindle motor Troque",
						unitM: "",
						unitI: "",
						valM: "115",
						valI: "115",
					},
				],
				feedRate: [
					{
						item: "X.Y Axis Rapid traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "40 / 40",
						valI: "1,575 / 1,575",
					},
					{
						item: "Z-Axis Rapid traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "40",
						valI: "1,575",
					},
					{
						item: "X.Y.Z Max. Cutting feed rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "12",
						valI: "472",
					},
				],
				atc: [
					{
						item: "ATC tool changer",
						unitM: "",
						unitI: "",
						valM: "Arm-Type ( Tool to tool)",
						valI: "Arm-Type ( Tool to tool)",
					},
					{
						item: "Tool Storage Capacity",
						unitM: "T",
						unitI: "T",
						valM: "24",
						valI: "24",
					},
					{
						item: "Tool Change Time (T-T)",
						unitM: "sec",
						unitI: "sec",
						valM: "1.8",
						valI: "1.8",
					},
					{
						item: "Max.Tool diameter*adjacent (with Neighbor)",
						unitM: "mm",
						unitI: "inch",
						valM: "100 x 300",
						valI: "3.94 x 11.81",
					},
					{
						item: "Max. Tools weight",
						unitM: "kg",
						unitI: "lb",
						valM: "7",
						valI: "15",
					},
				],
				motors: [
					{
						item: "Spindle Motor (Rate/Max.)",
						unitM: "kW",
						unitI: "HP",
						valM: "11 / 18.5",
						valI: "14.8 / 24.8",
					},
					{
						item: "X.Y Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.02",
					},
					{
						item: "Z Axis Servo Motor / w Breaks",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.02",
					},
				],
				accuracy: [
					{
						item: "Positioning Accuracy (JIS) Std.",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.008 / 300",
						valI: "± 0.008 / 300",
					},
					{
						item: "Repeatability  Accuracy (JIS) Std.",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.003",
						valI: "± 0.003",
					},
				],
				physical: [
					{
						item: "Power Required (kva/ Electricity Capcity)",
						unitM: "kva",
						unitI: "kva",
						valM: "25",
						valI: "25",
					},
					{
						item: "Air-Pressure Requirement",
						unitM: "kg/cm²",
						unitI: "psi",
						valM: "6 - 8",
						valI: "85 - 114",
					},
					{
						item: "External Dimensions ( L*W*H)",
						unitM: "mm",
						unitI: "inch",
						valM: "2700 x 2300 x 2550",
						valI: "106.3 x 90.55 x 100.39",
					},
					{
						item: "Gross.Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "6,450",
						valI: "14,220",
					},
					{
						item: "Ground Clearance ( height)",
						unitM: "mm",
						unitI: "inch",
						valM: "2600",
						valI: "102.36",
					},
				],
				standardAccessories: [
					"AIR- BLAST THROUGHT SPINDLE",
					"ARM-TYPE ATC-24 TOOLS",
					"AUTO LUBRICATION SYSTEM",
					"AUTO POWER OFF",
					"BT-40 DIRECT DRIVEN ( DDS) 12,000 Rpm",
					"CHIP FLUSH SYSTEM & NOBS",
					"FULL SPLASH GUARD",
					"HEAT EXCHANGER FOR CONTROLLER CABINET",
					"HIGH PRESSURE WATER & AIR-GUN",
					"RIDGIT TAPPING & THREADING SYSTEM OPERATION",
					"SCREW TYPE CHIP CONVEYOR + CART",
					"SPINDLE CUTTING COOLANT RING",
					"SPINDLE OIL COOLANT SYSTEM",
					"THREE COLOR LIGHT",
					"TOOL BOX & TOOLS",
					"TOOLS LENGTH MEASURING EQUIPMENT",
					"UBS INTERFACE",
					"WORK LAMP / WORK LED LIGHT",
				],
				optionalAccessories: [
					"4th AXIS ROTARY TABLE ( Ø125 / Ø170 / Ø210 / Ø255mm)",
					"CE APPROVED CERTIFICATION",
					"CE SAFETY DOORS SYSTEM",
					"CHAIN TYPE CHIP CONVEYOR + CART",
					"HEAVY SPINDLE MOTOR ( 11KW / 18.5KW)",
					"HEAVY SPINDLE TORQUE MOTOR",
					'LCD SCREEN 15"',
					"SEMI-AUTO ROTARY TABLE APC SYSTEM",
				],
			},
			{
				name: "NV-1370",
				image: "/nv/1370.png",
				download: "/documents/nv1370.pdf",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy",
						"Without counterweight design that enhances surface accuracy",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations",
					],
					image: "/nv/1370.png",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 48 /48 /40 m/min.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/nv/1370-2.png",
				},
				feature:
					"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy. Without counterweight design that enhances surface accuracy. A 198% increase in column span significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
				travel: [
					{
						item: "X-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "1,300",
						valI: "51.18",
					},
					{
						item: "Y-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "750",
						valI: "29.53",
					},
					{
						item: "Z-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "700",
						valI: "27.56",
					},
					{
						item: "Spindle Nose to table",
						unitM: "mm",
						unitI: "inch",
						valM: "120 - 820",
						valI: "4.72 - 32.28",
					},
					{
						item: "Spindle center to Z-Rail travel",
						unitM: "mm",
						unitI: "inch",
						valM: "780",
						valI: "30.71",
					},
					{
						item: "Three-Axis Guideway",
						unitM: "",
						unitI: "",
						valM: "X Y Z  load Roller Linear Guideway",
						valI: "X Y Z  load Roller Linear Guideway",
					},
				],
				table: [
					{
						item: "Table Size",
						unitM: "mm",
						unitI: "inch",
						valM: "1400 x 700",
						valI: "55.12 x 27.56",
					},
					{
						item: "T-Slot ( number*width*picth)",
						unitM: "mm",
						unitI: "inch",
						valM: "5 x 22 x 125",
						valI: "5 x 0.87 x 4.92",
					},
					{
						item: "Maximum table load",
						unitM: "kg",
						unitI: "lb",
						valM: "1,500",
						valI: "3,307",
					},
				],
				spindle: [
					{
						item: "Spindle taper",
						unitM: "",
						unitI: "",
						valM: "(Ø150mm)    BT-40",
						valI: "(Ø150mm)    BT-40",
					},
					{
						item: "Spindle Driven",
						unitM: "",
						unitI: "",
						valM: "Direct driven  ( DDS)",
						valI: "Direct driven  ( DDS)",
					},
					{
						item: "Spindle Speed",
						unitM: "rpm",
						unitI: "rpm",
						valM: "12,000",
						valI: "12,000",
					},
					{
						item: "Spindle motor Troque",
						unitM: "",
						unitI: "",
						valM: "115",
						valI: "115",
					},
				],
				feedRate: [
					{
						item: "X.Y Axis Rapid traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "36 / 36",
						valI: "1,417 / 1,417",
					},
					{
						item: "Z-Axis Rapid traverse",
						unitM: "m/min",
						unitI: "ipm",
						valM: "30",
						valI: "1,181",
					},
					{
						item: "X.Y.Z Max. Cutting feed rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "12",
						valI: "472",
					},
				],
				atc: [
					{
						item: "ATC tool changer",
						unitM: "",
						unitI: "",
						valM: "Arm-Type ( Tool to tool)",
						valI: "Arm-Type ( Tool to tool)",
					},
					{
						item: "Tool Storage Capacity",
						unitM: "T",
						unitI: "T",
						valM: "24",
						valI: "24",
					},
					{
						item: "Tool Change Time (T-T)",
						unitM: "sec",
						unitI: "sec",
						valM: "1.8",
						valI: "1.8",
					},
					{
						item: "Max.Tool diameter*adjacent (with Neighbor)",
						unitM: "mm",
						unitI: "inch",
						valM: "100 x 300",
						valI: "3.94 x 11.81",
					},
					{
						item: "Max. Tools weight",
						unitM: "kg",
						unitI: "lb",
						valM: "7",
						valI: "15",
					},
				],
				motors: [
					{
						item: "Spindle Motor (Rate/Max.)",
						unitM: "kW",
						unitI: "HP",
						valM: "11 / 18.5",
						valI: "14.8 / 24.8",
					},
					{
						item: "X.Y Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.02",
					},
					{
						item: "Z Axis Servo Motor / w Breaks",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.02",
					},
				],
				accuracy: [
					{
						item: "Positioning Accuracy (JIS) Std.",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.008 / 300",
						valI: "± 0.008 / 300",
					},
					{
						item: "Repeatability  Accuracy (JIS) Std.",
						unitM: "mm",
						unitI: "inch",
						valM: "± 0.003",
						valI: "± 0.003",
					},
				],
				physical: [
					{
						item: "Power Required (kva/ Electricity Capcity)",
						unitM: "kva",
						unitI: "kva",
						valM: "30",
						valI: "30",
					},
					{
						item: "Air-Pressure Requirement",
						unitM: "kg/cm²",
						unitI: "psi",
						valM: "6 - 8",
						valI: "85 - 114",
					},
					{
						item: "External Dimensions ( L*W*H)",
						unitM: "mm",
						unitI: "inch",
						valM: "3300 x 2700 x 2800",
						valI: "129.92 x 106.3 x 110.24",
					},
					{
						item: "Gross.Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "8,000",
						valI: "17,637",
					},
					{
						item: "Ground Clearance ( height)",
						unitM: "mm",
						unitI: "inch",
						valM: "3000",
						valI: "118.11",
					},
				],
				standardAccessories: [
					"AIR- BLAST THROUGHT SPINDLE",
					"ARM-TYPE ATC-24 TOOLS",
					"AUTO LUBRICATION SYSTEM",
					"AUTO POWER OFF",
					"BT-40 DIRECT DRIVEN ( DDS) 12,000 Rpm",
					"CHIP FLUSH SYSTEM & NOBS",
					"FULL SPLASH GUARD",
					"HEAT EXCHANGER FOR CONTROLLER CABINET",
					"HIGH PRESSURE WATER & AIR-GUN",
					"RIDGIT TAPPING & THREADING SYSTEM OPERATION",
					"SPINDLE CUTTING COOLANT RING",
					"SPINDLE OIL COOLANT SYSTEM",
					"THREE COLOR LIGHT",
					"TOOL BOX & TOOLS",
					"TOOLS LENGTH MEASURING EQUIPMENT",
					"UBS INTERFACE",
					"WORK LAMP / WORK LED LIGHT",
				],
				optionalAccessories: [
					"4th AXIS ROTARY TABLE ( Ø125 / Ø170 / Ø210 / Ø255mm)",
					"CE APPROVED CERTIFICATION",
					"CE SAFETY DOORS SYSTEM",
					"CHAIN TYPE CHIP CONVEYOR + CART",
					"HEAVY SPINDLE MOTOR ( 11KW / 18.5KW)",
					"HEAVY SPINDLE TORQUE MOTOR",
					'LCD SCREEN 15"',
					"SEMI-AUTO ROTARY TABLE APC SYSTEM",
				],
			},
		],
	},
	{
		id: 3,
		category: "Horizontal",
		download: "/documents/hmc.pdf",
		badge: "Industrial",
		title: "Heavy Duty HMC",
		model: "HMC-630A / 800A-B",
		image: "/hmc/hmc.png",
		specs: [
			{ icon: Zap, label: "Spindle", value: "8,000 RPM" },
			{ icon: Settings, label: "Tool Slots", value: "40 ATC" },
			{ icon: Disc, label: "Precision", value: "±0.010mm" },
			{ icon: ShieldCheck, label: "Warranty", value: "12 Monthss" },
		],
		models: [
			{
				name: "HMC-630A",
				image: "/hmc/hmc.png",
				download: "/documents/HMC630.pdf",
				feature:
					"High-rigidity Horizontal Machining Center designed for heavy-duty cutting and high-precision machining.",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy.",
						"Without counterweight design that enhances surface accuracy.",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity.",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations.",
					],
					image: "/feature.jpeg",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 24 m/min on X/Y/Z axes.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/structure.jpeg",
				},
				travel: [
					{
						item: "X-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "1050",
						valI: "41.34",
					},
					{
						item: "Y-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "850",
						valI: "33.46",
					},
					{
						item: "Z-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "950",
						valI: "37.40",
					},
					{
						item: "Spindle Nose To Pallet",
						unitM: "mm",
						unitI: "inch",
						valM: "150 - 1100",
						valI: "5.91 - 43.31",
					},
					{
						item: "Spindle Center To Pallet Surface",
						unitM: "mm",
						unitI: "inch",
						valM: "90 - 940",
						valI: "3.54 - 37.01",
					},
				],
				table: [
					{
						item: "Table Size",
						unitM: "mm",
						unitI: "inch",
						valM: "630 x 630",
						valI: "24.80 x 24.80",
					},
					{
						item: "Workbench Number",
						unitM: "",
						unitI: "",
						valM: "1 (Opt. 2)",
						valI: "1 (Opt. 2)",
					},
					{
						item: "Workbench Surface Configuration",
						unitM: "mm",
						unitI: "inch",
						valM: "M16 - 125",
						valI: "M16 - 4.92",
					},
					{
						item: "The Workbench Maximum Load",
						unitM: "kg",
						unitI: "lb",
						valM: "1200",
						valI: "2,646",
					},
					{
						item: "The Smallest Unit of Setting",
						unitM: "deg",
						unitI: "deg",
						valM: "1° (Opt. 0.001°)",
						valI: "1° (Opt. 0.001°)",
					},
				],
				spindle: [
					{
						item: "Spindle Taper",
						unitM: "",
						unitI: "",
						valM: "BT-50",
						valI: "BT-50",
					},
					{
						item: "Type Of Driving",
						unitM: "",
						unitI: "",
						valM: "Belt Type",
						valI: "Belt Type",
					},
					{
						item: "Spindle RPM",
						unitM: "rpm",
						unitI: "rpm",
						valM: "6000",
						valI: "6000",
					},
				],
				feedRate: [
					{
						item: "X, Z Axis Rapid Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "24",
						valI: "945",
					},
					{
						item: "Y Axis Rapid Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "24",
						valI: "945",
					},
					{
						item: "Max. Cutting Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "6",
						valI: "236",
					},
				],
				atc: [
					{
						item: "Arm Type (Tool to Tool)",
						unitM: "sec",
						unitI: "sec",
						valM: "4.5",
						valI: "4.5",
					},
					{
						item: "Tool Storage Capacity",
						unitM: "T",
						unitI: "T",
						valM: "30",
						valI: "30",
					},
					{
						item: "Tool Shank",
						unitM: "",
						unitI: "",
						valM: "BT-50",
						valI: "BT-50",
					},
					{
						item: "Max. Tool Diameter x Length",
						unitM: "mm",
						unitI: "inch",
						valM: "Ø200 x 350",
						valI: "Ø7.87 x 13.78",
					},
					{
						item: "Max. Tool Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "15",
						valI: "33",
					},
				],
				motors: [
					{
						item: "Spindle Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "15/18.5",
						valI: "20.1/24.8",
					},
					{
						item: "X Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.0",
					},
					{
						item: "Y Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3 (Brake)",
						valI: "4.0 (Brake)",
					},
					{
						item: "Z Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.0",
					},
					{
						item: "B Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "2.5",
						valI: "3.4",
					},
				],
				accuracy: [],
				physical: [
					{
						item: "Approximate Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "15,500 (A) / 17,000 (B)",
						valI: "34,171 (A) / 37,478 (B)",
					},
					{
						item: "Floor Space Measurement",
						unitM: "mm",
						unitI: "inch",
						valM: "6000 x 4600 x 3800",
						valI: "236.2 x 181.1 x 149.6",
					},
				],
				standardAccessories: [
					"Fully-Enclosed Splash Guard",
					"Electrical Cabinet with Heat Exchanger",
					"Work Lamp + Alarm Lamp",
					"High Pressured Coolant & Air Gun",
					"Spindle Air Blast & Coolant Nozzle",
					"Rigid Tapping",
					"Auto Lubrication System",
					"Editable CF Card Function",
					"Portable Hand Wheel (MPG)",
					"Auto interrupt & Power Off System",
					"Leveling Blocks & Screws",
					"Tool & Tool Box",
					"Chip Flushing System",
					"Spindle Coolant System",
					"Screw Type Chip Conveyor+Cart",
					"Operation Manual",
				],
				optionalAccessories: [
					"FANUC 0i-MF-(ALPHA PACKAGE)+AICC II",
					"Air Conditioner for Electrical Cabinet",
					"Chain type ATC-40T (40 taper)",
					"Chain type ATC-60T (40 taper)",
					"Chain type ATC-80T (40 taper)",
					"CTS 30 bar / 50 bar",
					"Heidenhain linear scales for XYZ",
					"Renishaw TS-27R (touch probe)",
					"Renishaw NC4 (laser probe)",
					"Renishaw OMP60 (workpiece probe)",
					"Transformer 30kva",
					"Oil Skimmer",
					"CE standard",
				],
			},
			{
				name: "HMC-800A-B",
				image: "/hmc/hmc2.png",
				download: "/documents/hmc800.pdf",
				feature:
					"High-rigidity Horizontal Machining Center designed for heavy-duty cutting and high-precision machining.",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy.",
						"Without counterweight design that enhances surface accuracy.",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity.",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations.",
					],
					image: "/feature.jpeg",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 24 m/min on X/Y/Z axes.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/structure.jpeg",
				},
				travel: [
					{
						item: "X-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "1300",
						valI: "51.18",
					},
					{
						item: "Y-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "1000",
						valI: "39.37",
					},
					{
						item: "Z-Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "1050",
						valI: "41.34",
					},
					{
						item: "Spindle Nose To Pallet",
						unitM: "mm",
						unitI: "inch",
						valM: "150 - 1200",
						valI: "5.91 - 47.24",
					},
					{
						item: "Spindle Center To Pallet Surface",
						unitM: "mm",
						unitI: "inch",
						valM: "90 - 1090",
						valI: "3.54 - 42.91",
					},
				],
				table: [
					{
						item: "Table Size",
						unitM: "mm",
						unitI: "inch",
						valM: "800 x 800",
						valI: "31.50 x 31.50",
					},
					{
						item: "Workbench Number",
						unitM: "",
						unitI: "",
						valM: "1 (Opt. 2)",
						valI: "1 (Opt. 2)",
					},
					{
						item: "Workbench Surface Configuration",
						unitM: "mm",
						unitI: "inch",
						valM: "M16 - 160",
						valI: "M16 - 6.30",
					},
					{
						item: "The Workbench Maximum Load",
						unitM: "kg",
						unitI: "lb",
						valM: "1300 - 2000",
						valI: "2,866 - 4,409",
					},
					{
						item: "The Smallest Unit of Setting",
						unitM: "deg",
						unitI: "deg",
						valM: "1° (Opt. 0.001°)",
						valI: "1° (Opt. 0.001°)",
					},
				],
				spindle: [
					{
						item: "Spindle Taper",
						unitM: "",
						unitI: "",
						valM: "BT-50",
						valI: "BT-50",
					},
					{
						item: "Type Of Driving",
						unitM: "",
						unitI: "",
						valM: "Belt Type",
						valI: "Belt Type",
					},
					{
						item: "Spindle RPM",
						unitM: "rpm",
						unitI: "rpm",
						valM: "6000",
						valI: "6000",
					},
				],
				feedRate: [
					{
						item: "X, Z Axis Rapid Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "24",
						valI: "945",
					},
					{
						item: "Y Axis Rapid Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "24",
						valI: "945",
					},
					{
						item: "Max. Cutting Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "6",
						valI: "236",
					},
				],
				atc: [
					{
						item: "Arm Type (Tool to Tool)",
						unitM: "sec",
						unitI: "sec",
						valM: "4.5",
						valI: "4.5",
					},
					{
						item: "Tool Storage Capacity",
						unitM: "T",
						unitI: "T",
						valM: "30",
						valI: "30",
					},
					{
						item: "Tool Shank",
						unitM: "",
						unitI: "",
						valM: "BT-50",
						valI: "BT-50",
					},
					{
						item: "Max. Tool Diameter x Length",
						unitM: "mm",
						unitI: "inch",
						valM: "Ø200 x 350",
						valI: "Ø7.87 x 13.78",
					},
					{
						item: "Max. Tool Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "15",
						valI: "33",
					},
				],
				motors: [
					{
						item: "Spindle Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "15/18.5",
						valI: "20.1/24.8",
					},
					{
						item: "X Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.0",
					},
					{
						item: "Y Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3 (Brake)",
						valI: "4.0 (Brake)",
					},
					{
						item: "Z Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.0",
					},
					{
						item: "B Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "2.5",
						valI: "3.4",
					},
				],
				accuracy: [],
				physical: [
					{
						item: "Approximate Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "16,500 (A) / 20,000 (B)",
						valI: "36,376 (A) / 44,092 (B)",
					},
					{
						item: "Floor Space Measurement",
						unitM: "mm",
						unitI: "inch",
						valM: "6000 x 5000 x 3800",
						valI: "236.2 x 196.9 x 149.6",
					},
				],
				standardAccessories: [
					"Fully-Enclosed Splash Guard",
					"Electrical Cabinet with Heat Exchanger",
					"Work Lamp + Alarm Lamp",
					"High Pressured Coolant & Air Gun",
					"Spindle Air Blast & Coolant Nozzle",
					"Rigid Tapping",
					"Auto Lubrication System",
					"Editable CF Card Function",
					"Portable Hand Wheel (MPG)",
					"Auto interrupt & Power Off System",
					"Leveling Blocks & Screws",
					"Tool & Tool Box",
					"Chip Flushing System",
					"Spindle Coolant System",
					"Screw Type Chip Conveyor+Cart",
					"Operation Manual",
				],
				optionalAccessories: [
					"FANUC 0i-MF-(ALPHA PACKAGE)+AICC II",
					"Air Conditioner for Electrical Cabinet",
					"Chain type ATC-40T (40 taper)",
					"Chain type ATC-60T (40 taper)",
					"Chain type ATC-80T (40 taper)",
					"CTS 30 bar / 50 bar",
					"Heidenhain linear scales for XYZ",
					"Renishaw TS-27R (touch probe)",
					"Renishaw NC4 (laser probe)",
					"Renishaw OMP60 (workpiece probe)",
					"Transformer 30kva",
					"Oil Skimmer",
					"CE standard",
				],
			},
		],
	},
	{
		id: 4,
		category: "Lathe",
		download: "/documents/SLM.pdf",
		badge: "High Precision",
		title: "Slant Bed CNC Lathe",
		model: "3015S / 3605M",
		image: "/hbd/hd1.png",
		specs: [
			{ icon: Zap, label: "Spindle", value: "2,000 - 2,800 RPM" },
			{ icon: Settings, label: "Turret", value: "12 Stations" },
			{ icon: Disc, label: "Chuck Size", value: '12" - 15"' },
			{ icon: ShieldCheck, label: "Warranty", value: "2 Years" },
		],
		models: [
			{
				name: "3015S",
				image: "/hbd/hd1.png",
				download: "/documents/3105S.pdf",
				feature:
					"High Precision Slant Bed CNC Lathe 3015S designed for heavy duty turning applications.",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy.",
						"Without counterweight design that enhances surface accuracy.",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity.",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations.",
					],
					image: "/feature.jpeg",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 24 m/min on X/Y/Z axes.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/structure.jpeg",
				},
				travel: [
					{
						item: "X-Axis Travel Distance",
						unitM: "mm",
						unitI: "inch",
						valM: "260",
						valI: "10.24",
					},
					{
						item: "Z-Axis Travel Distance",
						unitM: "mm",
						unitI: "inch",
						valM: "730 [1,350]",
						valI: "28.74 [53.15]",
					},
				],
				table: [
					{
						item: "Max. Swing",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ740",
						valI: "Φ29.13",
					},
					{
						item: "Max. Rotational Dia",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ656",
						valI: "Φ25.83",
					},
					{
						item: "Max. Turning Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ500",
						valI: "Φ19.69",
					},
					{
						item: "Max. Turning Length",
						unitM: "mm",
						unitI: "inch",
						valM: "708 [1,288]",
						valI: "27.87 [50.71]",
					},
					{
						item: "Bar Working Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ74",
						valI: "Φ2.91",
					},
					{
						item: "Tailstock Quill Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ100",
						valI: "Φ3.94",
					},
				],
				spindle: [
					{
						item: "Spindle Speed (Belt Type)",
						unitM: "rpm",
						unitI: "rpm",
						valM: "2800",
						valI: "2800",
					},
					{
						item: "Spindle Nose",
						unitM: "",
						unitI: "",
						valM: "12 inch Chuck A2-8",
						valI: "12 inch Chuck A2-8",
					},
					{
						item: "Spindle Through Hole",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ91",
						valI: "Φ3.58",
					},
				],
				feedRate: [
					{
						item: "Rapid Traverse (X/Z)",
						unitM: "m/min",
						unitI: "ipm",
						valM: "24 / 30",
						valI: "945 / 1181",
					},
				],
				atc: [
					{
						item: "No. of Tool Stations",
						unitM: "",
						unitI: "",
						valM: "12",
						valI: "12",
					},
					{
						item: "OD Tool Size",
						unitM: "mm",
						unitI: "inch",
						valM: "25",
						valI: "0.98",
					},
					{
						item: "Boring Bar Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "50",
						valI: "1.97",
					},
					{
						item: "Indexing Time",
						unitM: "sec",
						unitI: "sec",
						valM: "0.2",
						valI: "0.2",
					},
					{
						item: "Tailstock Quill Taper",
						unitM: "",
						unitI: "",
						valM: "MT5",
						valI: "MT5",
					},
				],
				motors: [
					{
						item: "Main Spindle Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "15 / 18.5",
						valI: "20.1 / 24.8",
					},
					{
						item: "Coolant Motor Power",
						unitM: "kW",
						unitI: "HP",
						valM: "0.4",
						valI: "0.54",
					},
				],
				accuracy: [],
				physical: [
					{
						item: "Power Capacity",
						unitM: "kVA",
						unitI: "kVA",
						valM: "30",
						valI: "30",
					},
					{
						item: "Machine Height",
						unitM: "mm",
						unitI: "inch",
						valM: "1755",
						valI: "69.09",
					},
					{
						item: "Machine Dimension (LxW)",
						unitM: "mm",
						unitI: "inch",
						valM: "3284 x 1817",
						valI: "129.3 x 71.5",
					},
					{
						item: "Machine Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "5,800 [7,000]",
						valI: "12,787 [15,432]",
					},
				],
				standardAccessories: [
					"Hydraulic Chuck",
					"Soft Jaws",
					"Hydraulic Turret",
					"Coolant System",
					"Work Light",
					"Warning Light",
					"Tool Box & Tools",
					"Manuals",
				],
				optionalAccessories: [
					"Chip Conveyor",
					"Tool Setter",
					"Auto Door",
					"Bar Feeder Interface",
					"Oil Skimmer",
					"High Pressure Coolant",
				],
			},
			{
				name: "3605M",
				image: "/hbd/hd2.png",
				download: "/documents/3605M.pdf",
				feature:
					"High Precision Slant Bed CNC Lathe 3605M designed for heavy duty turning applications with large capacity.",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy.",
						"Without counterweight design that enhances surface accuracy.",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity.",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations.",
					],
					image: "/feature.jpeg",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 24 m/min on X/Y/Z axes.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/structure.jpeg",
				},
				travel: [
					{
						item: "X-Axis Travel Distance",
						unitM: "mm",
						unitI: "inch",
						valM: "295",
						valI: "11.61",
					},
					{
						item: "Z-Axis Travel Distance",
						unitM: "mm",
						unitI: "inch",
						valM: "1350 [2150/3150]",
						valI: "53.15 [84.6/124.0]",
					},
				],
				table: [
					{
						item: "Max. Swing",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ940",
						valI: "Φ37.01",
					},
					{
						item: "Max. Rotational Dia",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ855",
						valI: "Φ33.66",
					},
					{
						item: "Max. Turning Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ540",
						valI: "Φ21.26",
					},
					{
						item: "Max. Turning Length",
						unitM: "mm",
						unitI: "inch",
						valM: "1342 [2120/3120]",
						valI: "52.83 [83.5/122.8]",
					},
					{
						item: "Bar Working Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ119",
						valI: "Φ4.69",
					},
					{
						item: "Tailstock Quill Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ100",
						valI: "Φ3.94",
					},
				],
				spindle: [
					{
						item: "Spindle Speed (Belt Type)",
						unitM: "rpm",
						unitI: "rpm",
						valM: "2000",
						valI: "2000",
					},
					{
						item: "Spindle Nose",
						unitM: "",
						unitI: "",
						valM: "15 inch Chuck A2-11",
						valI: "15 inch Chuck A2-11",
					},
					{
						item: "Spindle Through Hole",
						unitM: "mm",
						unitI: "inch",
						valM: "Φ131",
						valI: "Φ5.16",
					},
				],
				feedRate: [
					{
						item: "Rapid Traverse (X/Z)",
						unitM: "m/min",
						unitI: "ipm",
						valM: "24 / 30",
						valI: "945 / 1181",
					},
				],
				atc: [
					{
						item: "No. of Tool Stations",
						unitM: "",
						unitI: "",
						valM: "12",
						valI: "12",
					},
					{
						item: "OD Tool Size",
						unitM: "mm",
						unitI: "inch",
						valM: "25",
						valI: "0.98",
					},
					{
						item: "Boring Bar Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "50",
						valI: "1.97",
					},
					{
						item: "Indexing Time",
						unitM: "sec",
						unitI: "sec",
						valM: "0.2",
						valI: "0.2",
					},
					{
						item: "Tailstock Quill Taper",
						unitM: "",
						unitI: "",
						valM: "MT5",
						valI: "MT5",
					},
				],
				motors: [
					{
						item: "Main Spindle Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "15 / 18.5",
						valI: "20.1 / 24.8",
					},
					{
						item: "Coolant Motor Power",
						unitM: "kW",
						unitI: "HP",
						valM: "0.4",
						valI: "0.54",
					},
				],
				accuracy: [],
				physical: [
					{
						item: "Power Capacity",
						unitM: "kVA",
						unitI: "kVA",
						valM: "35",
						valI: "35",
					},
					{
						item: "Machine Height",
						unitM: "mm",
						unitI: "inch",
						valM: "1857",
						valI: "73.11",
					},
					{
						item: "Machine Dimension (LxW)",
						unitM: "mm",
						unitI: "inch",
						valM: "4195 x 1978",
						valI: "165.2 x 77.9",
					},
					{
						item: "Machine Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "7,200 [8,500/10,000]",
						valI: "15,873 [18,739/22,046]",
					},
				],
				standardAccessories: [
					"Hydraulic Chuck",
					"Soft Jaws",
					"Hydraulic Turret",
					"Coolant System",
					"Work Light",
					"Warning Light",
					"Tool Box & Tools",
					"Manuals",
				],
				optionalAccessories: [
					"Chip Conveyor",
					"Tool Setter",
					"Auto Door",
					"Bar Feeder Interface",
					"Oil Skimmer",
					"High Pressure Coolant",
				],
			},
		],
	},
	{
		id: 5,
		category: "Vertical",
		badge: "Reliable",
		title: "Veritcal Lathe Machine",
		model: "VLT-550 / 750 ",
		image: "/vt/vlt 550.png",
		download: "/documents/vlt.pdf",
		specs: [
			{ icon: Zap, label: "Spindle", value: "50 - 2000 rpm" },
			{ icon: Settings, label: "Slots", value: "8 ATC" },
			{ icon: Disc, label: "Spindle Nose.", value: "A2-8" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
		models: [
			{
				name: "VLT-550",
				image: "/vt/vlt 550.png",
				download: "/documents/VLT-550.pdf",
				feature:
					"High-performance CNC Vertical Lathe designed for heavy-duty turning operations with a compact footprint.",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy",
						"Without counterweight design that enhances surface accuracy",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations",
					],
					image: "/vt/vlt-750.png",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 48 /48 /40 m/min.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/vt/vlt 550.png",
				},
				travel: [
					{
						item: "X - Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "+300 / -30",
						valI: "+11.81 / -1.18",
					},
					{
						item: "Z - Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "580",
						valI: "22.83",
					},
				],
				table: [
					{
						item: "Chuck Diameter",
						unitM: "inch",
						unitI: "inch",
						valM: "12",
						valI: "12",
					},
					{
						item: "Max. Swing",
						unitM: "mm",
						unitI: "inch",
						valM: "650",
						valI: "25.59",
					},
					{
						item: "Max. Turning Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "550",
						valI: "21.65",
					},
					{
						item: "Max. Turning Length",
						unitM: "mm",
						unitI: "inch",
						valM: "550",
						valI: "21.65",
					},
					{
						item: "Maximum Workpiece Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "500",
						valI: "1,102",
					},
				],
				spindle: [
					{
						item: "Spindle Nose",
						unitM: "",
						unitI: "",
						valM: "A2-8",
						valI: "A2-8",
					},
					{
						item: "Spindle Bearing Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "130",
						valI: "5.12",
					},
					{
						item: "Spindle Speed",
						unitM: "rpm",
						unitI: "rpm",
						valM: "50-2000",
						valI: "50-2000",
					},
				],
				feedRate: [
					{
						item: "X Axis Rapid Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "12",
						valI: "472",
					},
					{
						item: "Z Axis Rapid Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "20",
						valI: "787",
					},
				],
				atc: [
					{
						item: "Turret Type",
						unitM: "",
						unitI: "",
						valM: "Horizontal",
						valI: "Horizontal",
					},
					{
						item: "Number of Tools",
						unitM: "T",
						unitI: "T",
						valM: "8",
						valI: "8",
					},
					{
						item: "Cutter Size",
						unitM: "mm",
						unitI: "inch",
						valM: "φ32 (Opt. φ50)",
						valI: "φ1.26 (Opt. φ1.97)",
					},
				],
				motors: [
					{
						item: "Spindle Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "15 / 18.5",
						valI: "20.1 / 24.8",
					},
					{
						item: "X Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.0",
					},
					{
						item: "Z Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3 (with Brake)",
						valI: "4.0 (with Brake)",
					},
					{
						item: "Coolant Pump Motor",
						unitM: "W",
						unitI: "HP",
						valM: "750",
						valI: "1.0",
					},
					{
						item: "Hydraulic Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "2.2",
						valI: "2.95",
					},
				],
				accuracy: [], // Accuracy data was not explicitly listed in the source file
				physical: [
					{
						item: "Approximate Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "7,000",
						valI: "15,432",
					},
					{
						item: "Floor Space Measurement",
						unitM: "mm",
						unitI: "inch",
						valM: "2000 x 3660 x 3100",
						valI: "78.7 x 144.1 x 122.0",
					},
					{
						item: "Pneumatic Requirement",
						unitM: "kg/cm²",
						unitI: "psi",
						valM: "≧ 6.5",
						valI: "≧ 92",
					},
					{
						item: "Power Capacity",
						unitM: "KVA",
						unitI: "KVA",
						valM: "28",
						valI: "28",
					},
					{
						item: "Power Voltage",
						unitM: "",
						unitI: "",
						valM: "3 phase AC 220V ±5%",
						valI: "3 phase AC 220V ±5%",
					},
				],
				standardAccessories: [
					"Fanuc 0i-TF Controller",
					'10.4" LCD screen',
					"Leveling Bolts and Leveling Blocks",
					"Tool box & Tools",
					"Work lamp",
					"Alarm Lamp",
					"Auto power off",
					"Auto lubrication system",
					"Chain Type Chip Conveyor with Cart",
					'12" three jaw solid oil pressure chuck',
					"Chip flush",
					"Standard knife dish",
					"Heat exchanger for control cabinet",
					"Remote manual pulse generator",
					'12" soft JAWS',
					"High and low pressure loop of collet",
					"Air gun",
					"Full splash guard",
					"System operation manual",
					"Machine manual",
				],
				optionalAccessories: [
					"Automatic Door System",
					"Oil Skimmer",
					"Air Conditioner for Electrical Cabinet",
					"Hard-Jaw",
					"Oil Mist Collector System",
					"ZF Gearbox",
					"Coolant Intercooling System",
					"Safety Door Switch",
					"Heidenhain Optical Linear Scales",
					"Paper Bank Filter System",
					'18" three jaw solid oil pressure chuck',
				],
			},
			{
				name: "VLT-750",
				image: "/vt/vlt-750.png",
				download: "/documents/vlt-750.pdf",
				feature:
					"Heavy-duty CNC Vertical Lathe featuring a large 15-inch chuck and increased turning capacity.",
				feature1: {
					data: [
						"The rigid inverted Y-shaped structure has full stroke support without overhang that guarantees the most dynamic leveling accuracy",
						"Without counterweight design that enhances surface accuracy",
						"Significantly improves load-bearing capacity and rigidity, enhancing the structure's stability and reliability.",
						"Spindle ram rigidity and empower the spindle & heavy motor load capacity",
						"High-rigidity design ensures continuous accuracy and stability during heavy operations",
					],
					image: "/vt/vlt 550.png",
				},
				feature2: {
					data: [
						"All axes are equipped with roller linear guides and Medium-size ball-screws to ensure stability and longer life under smooth & heavy cutting.",
						"Fast Rapid Speed 48 /48 /40 m/min.",
						"The Y-axis is equipped with 4 roller guideways for better rigidity.",
						"High quality linear ways guide and high pitch ball-screw makes the difference during milling.",
						"Super-fast cut and complex applications.",
					],
					image: "/vt/vlt-750.png",
				},
				travel: [
					{
						item: "X - Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "+400 / -30",
						valI: "+15.75 / -1.18",
					},
					{
						item: "Z - Axis Travel",
						unitM: "mm",
						unitI: "inch",
						valM: "700",
						valI: "27.56",
					},
				],
				table: [
					{
						item: "Chuck Diameter",
						unitM: "inch",
						unitI: "inch",
						valM: "15",
						valI: "15",
					},
					{
						item: "Max. Swing",
						unitM: "mm",
						unitI: "inch",
						valM: "800",
						valI: "31.50",
					},
					{
						item: "Max. Turning Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "750",
						valI: "29.53",
					},
					{
						item: "Max. Turning Length",
						unitM: "mm",
						unitI: "inch",
						valM: "650",
						valI: "25.59",
					},
					{
						item: "Maximum Workpiece Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "1,000",
						valI: "2,205",
					},
				],
				spindle: [
					{
						item: "Spindle Nose",
						unitM: "",
						unitI: "",
						valM: "A2-11",
						valI: "A2-11",
					},
					{
						item: "Spindle Bearing Diameter",
						unitM: "mm",
						unitI: "inch",
						valM: "160",
						valI: "6.30",
					},
					{
						item: "Spindle Speed",
						unitM: "rpm",
						unitI: "rpm",
						valM: "50-2000",
						valI: "50-2000",
					},
				],
				feedRate: [
					{
						item: "X Axis Rapid Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "12",
						valI: "472",
					},
					{
						item: "Z Axis Rapid Feed Rate",
						unitM: "m/min",
						unitI: "ipm",
						valM: "20",
						valI: "787",
					},
				],
				atc: [
					{
						item: "Turret Type",
						unitM: "",
						unitI: "",
						valM: "Horizontal",
						valI: "Horizontal",
					},
					{
						item: "Number of Tools",
						unitM: "T",
						unitI: "T",
						valM: "8",
						valI: "8",
					},
					{
						item: "Cutter Size",
						unitM: "mm",
						unitI: "inch",
						valM: "φ32 / φ50",
						valI: "φ1.26 / φ1.97",
					},
				],
				motors: [
					{
						item: "Controller System",
						unitM: "",
						unitI: "",
						valM: 'Fanuc 0i-TF Plus (10.4" LCD)',
						valI: 'Fanuc 0i-TF Plus (10.4" LCD)',
					},
					{
						item: "Spindle Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "15 / 18.5",
						valI: "20.1 / 24.8",
					},
					{
						item: "X Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3",
						valI: "4.0",
					},
					{
						item: "Z Axis Servo Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "3 (with Brake)",
						valI: "4.0 (with Brake)",
					},
					{
						item: "Coolant Pump Motor",
						unitM: "W",
						unitI: "HP",
						valM: "750",
						valI: "1.0",
					},
					{
						item: "Hydraulic Motor",
						unitM: "kW",
						unitI: "HP",
						valM: "2.2",
						valI: "2.95",
					},
				],
				accuracy: [],
				physical: [
					{
						item: "Approximate Weight",
						unitM: "kg",
						unitI: "lb",
						valM: "11,000",
						valI: "24,251",
					},
					{
						item: "Floor Space Measurement",
						unitM: "mm",
						unitI: "inch",
						valM: "2250 x 3990 x 3320",
						valI: "88.6 x 157.1 x 130.7",
					},
					{
						item: "Pneumatic Requirement",
						unitM: "kg/cm²",
						unitI: "psi",
						valM: "≧ 6.5",
						valI: "≧ 92",
					},
					{
						item: "Power Capacity",
						unitM: "KVA",
						unitI: "KVA",
						valM: "28",
						valI: "28",
					},
					{
						item: "Power Voltage",
						unitM: "",
						unitI: "",
						valM: "3 phase AC 220V ±5%",
						valI: "3 phase AC 220V ±5%",
					},
				],
				standardAccessories: [
					"Fanuc 0i-TF Controller",
					'10.4" LCD screen',
					"Leveling Bolts and Leveling Blocks",
					"Tool box & Tools",
					"Work lamp",
					"Alarm Lamp",
					"Auto power off",
					"Auto lubrication system",
					"Chain Type Chip Conveyor with Cart",
					'15" three jaw solid oil pressure chuck',
					"Chip flush",
					"Standard knife dish",
					"Heat exchanger for control cabinet",
					"Remote manual pulse generator",
					'12" soft JAWS',
					"High and low pressure loop of collet",
					"Air gun",
					"Full splash guard",
					"System operation manual",
					"Machine manual",
				],
				optionalAccessories: [
					"Automatic Door System",
					"Oil Skimmer",
					"Air Conditioner for Electrical Cabinet",
					"Hard-Jaw",
					"Oil Mist Collector System",
					"ZF Gearbox",
					"Coolant Intercooling System",
					"Safety Door Switch",
					"Heidenhain Optical Linear Scales",
					"Paper Bank Filter System",
					'20" three jaw solid oil pressure chuck',
				],
			},
		],
	},
	{
		id: 6,
		category: "Vertical",
		badge: "Elite",
		title: "Ultra VMC",
		model: "VMC-MAX-Z",
		image:
			"https://media.istockphoto.com/id/2149279878/photo/shot-blasting-man-in-production-the-sandblaster-is-sending-to-steel-material-abrasive.jpg?s=612x612&w=0&k=20&c=iVntK-1R42eULcv0hVGUEWlhHe0fweeAXU5sZQ4Dz04=",
		specs: [
			{ icon: Zap, label: "Spindle", value: "24k RPM" },
			{ icon: Settings, label: "Slots", value: "60 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.001" },
			{ icon: ShieldCheck, label: "Warr.", value: "5 Yr" },
		],
	},
	{
		id: 7,
		category: "Horizontal",
		badge: "Performance",
		title: "Horizontal Machining Center",
		model: "HMC-630",
		image:
			"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "15,000 RPM" },
			{ icon: Settings, label: "Tool Slots", value: "24 ATC" },
			{ icon: Disc, label: "Precision", value: "±0.003mm" },
			{ icon: ShieldCheck, label: "Warranty", value: "2 Years" },
		],
	},
	{
		id: 8,
		category: "Horizontal",
		badge: "Pro",
		title: "Pro HMC",
		model: "HMC-800",
		image:
			"https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "12k RPM" },
			{ icon: Settings, label: "Slots", value: "40 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.003" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 9,
		category: "Horizontal",
		badge: "XL",
		title: "Heavy HMC",
		model: "HMC-1250",
		image:
			"https://plus.unsplash.com/premium_photo-1682144880138-9f1c0bfe6fa7?w=600&auto=format&fit=crop&q=60",
		specs: [
			{ icon: Zap, label: "Spindle", value: "8k RPM" },
			{ icon: Settings, label: "Slots", value: "80 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.008" },
			{ icon: ShieldCheck, label: "Warr.", value: "3 Yr" },
		],
	},
	{
		id: 10,
		category: "Horizontal",
		badge: "Compact",
		title: "Mini HMC",
		model: "HMC-400-S",
		image:
			"https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "18k RPM" },
			{ icon: Settings, label: "Slots", value: "20 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.002" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 11,
		category: "Horizontal",
		badge: "New",
		title: "Smart HMC",
		model: "HMC-AI-80",
		image:
			"https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "15k RPM" },
			{ icon: Settings, label: "Slots", value: "60 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.001" },
			{ icon: ShieldCheck, label: "Warr.", value: "5 Yr" },
		],
	},
	{
		id: 12,
		category: "Horizontal",
		badge: "Dual Pallet",
		title: "Production HMC",
		model: "HMC-DUPLEX",
		image:
			"https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "10k RPM" },
			{ icon: Settings, label: "Slots", value: "120 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.005" },
			{ icon: ShieldCheck, label: "Warr.", value: "3 Yr" },
		],
	},
	{
		id: 13,
		category: "5-Axis",
		badge: "Premium",
		title: "5-Axis Machining Center",
		model: "5AX-500",
		image:
			"https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "18,000 RPM" },
			{ icon: Settings, label: "Tool Slots", value: "24 ATC" },
			{ icon: Disc, label: "Precision", value: "±0.002mm" },
			{ icon: ShieldCheck, label: "Warranty", value: "3 Years" },
		],
	},
	{
		id: 14,
		category: "5-Axis",
		badge: "Aero",
		title: "Aerospace 5-Axis",
		model: "5AX-700-AIR",
		image:
			"https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "24k RPM" },
			{ icon: Settings, label: "Slots", value: "48 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.001" },
			{ icon: ShieldCheck, label: "Warr.", value: "5 Yr" },
		],
	},
	{
		id: 15,
		category: "5-Axis",
		badge: "Compact",
		title: "Lab 5-Axis",
		model: "5AX-MINI",
		image:
			"https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "30k RPM" },
			{ icon: Settings, label: "Slots", value: "12 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.002" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 16,
		category: "5-Axis",
		badge: "Elite",
		title: "Titanium 5AX",
		model: "5AX-ULTRA-900",
		image:
			"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "15k RPM" },
			{ icon: Settings, label: "Slots", value: "120 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.0005" },
			{ icon: ShieldCheck, label: "Warr.", value: "5 Yr" },
		],
	},
	{
		id: 17,
		category: "5-Axis",
		badge: "Versatile",
		title: "Universal 5-Axis",
		model: "U-5AX-600",
		image:
			"https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "20k RPM" },
			{ icon: Settings, label: "Slots", value: "32 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.002" },
			{ icon: ShieldCheck, label: "Warr.", value: "3 Yr" },
		],
	},
	{
		id: 18,
		category: "5-Axis",
		badge: "High Torque",
		title: "Milling Center",
		model: "5AX-TORQUE",
		image:
			"https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "6k RPM" },
			{ icon: Settings, label: "Slots", value: "40 ATC" },
			{ icon: Disc, label: "Prec.", value: "0.004" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 19,
		category: "Turning",
		badge: "New",
		title: "CNC Lathe",
		model: "NL-250",
		image:
			"https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "4k RPM" },
			{ icon: Settings, label: "Turret", value: "10 Pos" },
			{ icon: Disc, label: "Prec.", value: "0.008" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 20,
		category: "Turning",
		badge: "Pro",
		title: "Pro Lathe",
		model: "NL-400",
		image:
			"https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "3k RPM" },
			{ icon: Settings, label: "Turret", value: "12 Pos" },
			{ icon: Disc, label: "Prec.", value: "0.008" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 21,
		category: "Turning",
		badge: "Dual",
		title: "Twin Spindle Lathe",
		model: "TSL-200",
		image:
			"https://plus.unsplash.com/premium_photo-1664298925852-a10f7112c548?w=600&auto=format&fit=crop&q=60",
		specs: [
			{ icon: Zap, label: "Spindle", value: "6k RPM" },
			{ icon: Settings, label: "Turret", value: "24 Pos" },
			{ icon: Disc, label: "Prec.", value: "0.005" },
			{ icon: ShieldCheck, label: "Warr.", value: "3 Yr" },
		],
	},
	{
		id: 22,
		category: "Turning",
		badge: "Swift",
		title: "Swiss Turn",
		model: "SW-12",
		image:
			"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "10k RPM" },
			{ icon: Settings, label: "Turret", value: "Live" },
			{ icon: Disc, label: "Prec.", value: "0.001" },
			{ icon: ShieldCheck, label: "Warr.", value: "3 Yr" },
		],
	},
	{
		id: 23,
		category: "Turning",
		badge: "Heavy",
		title: "Bore Lathe",
		model: "NL-800-B",
		image:
			"https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "1.5k RPM" },
			{ icon: Settings, label: "Turret", value: "8 Pos" },
			{ icon: Disc, label: "Prec.", value: "0.012" },
			{ icon: ShieldCheck, label: "Warr.", value: "5 Yr" },
		],
	},
	{
		id: 24,
		category: "Turning",
		badge: "Fast",
		title: "Precision Turning",
		model: "NL-FAST-40",
		image:
			"https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Spindle", value: "8k RPM" },
			{ icon: Settings, label: "Turret", value: "16 Pos" },
			{ icon: Disc, label: "Prec.", value: "0.002" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 25,
		category: "Surface Grinder",
		badge: "Manual",
		title: "Surface Grinder",
		model: "SG-150",
		image:
			"https://images.unsplash.com/photo-1598302936625-6075fbd98dd7?w=600&auto=format&fit=crop&q=60",
		specs: [
			{ icon: Zap, label: "Wheel", value: "3k RPM" },
			{ icon: Settings, label: "Table", value: "Manual" },
			{ icon: Disc, label: "Prec.", value: "0.002" },
			{ icon: ShieldCheck, label: "Warr.", value: "1 Yr" },
		],
	},
	{
		id: 26,
		category: "Surface Grinder",
		badge: "Auto",
		title: "Auto Grinder",
		model: "SG-300A",
		image:
			"https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Wheel", value: "3k RPM" },
			{ icon: Settings, label: "Table", value: "Hydraulic" },
			{ icon: Disc, label: "Prec.", value: "0.002" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 27,
		category: "Surface Grinder",
		badge: "Large",
		title: "Heavy Grinder",
		model: "SG-800HD",
		image:
			"https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Wheel", value: "2k RPM" },
			{ icon: Settings, label: "Table", value: "Auto" },
			{ icon: Disc, label: "Prec.", value: "0.005" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 28,
		category: "Surface Grinder",
		badge: "Precision",
		title: "Ultra Grinder",
		model: "SG-UL-1",
		image:
			"https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Wheel", value: "5k RPM" },
			{ icon: Settings, label: "Table", value: "CNC" },
			{ icon: Disc, label: "Prec.", value: "0.0005" },
			{ icon: ShieldCheck, label: "Warr.", value: "5 Yr" },
		],
	},
	{
		id: 29,
		category: "Surface Grinder",
		badge: "Compact",
		title: "Toolroom Grinder",
		model: "SG-MINI-X",
		image:
			"https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Wheel", value: "4.5k RPM" },
			{ icon: Settings, label: "Table", value: "Manual" },
			{ icon: Disc, label: "Prec.", value: "0.002" },
			{ icon: ShieldCheck, label: "Warr.", value: "2 Yr" },
		],
	},
	{
		id: 30,
		category: "Surface Grinder",
		badge: "Industrial",
		title: "Rotary Grinder",
		model: "SG-ROT-50",
		image:
			"https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&q=80&w=1000",
		specs: [
			{ icon: Zap, label: "Wheel", value: "1.5k RPM" },
			{ icon: Settings, label: "Table", value: "Rotary" },
			{ icon: Disc, label: "Prec.", value: "0.008" },
			{ icon: ShieldCheck, label: "Warr.", value: "3 Yr" },
		],
	},
];

const filters: FilterOption[] = [
	{ name: "Vertical", count: "6 Models" },
	{ name: "Horizontal", count: "6 Models" },
	{ name: "5-Axis", count: "6 Models" },
	{ name: "Turning", count: "6 Models" },
	{ name: "Surface Grinder", count: "6 Models" },
	{ name: "All", count: "30 Models" },
];

const ProductContext = createContext<ProductContextType | undefined>(undefined);

export function ProductProvider({ children }: { children: React.ReactNode }) {
	return (
		<ProductContext.Provider value={{ products, filters }}>
			{children}
		</ProductContext.Provider>
	);
}

export function useProducts() {
	const context = useContext(ProductContext);
	if (!context) {
		throw new Error("useProducts must be used within ProductProvider");
	}
	return context;
}
